#
#logging.level:
#  org.hibernate.SQL: debug
#  #org.hibernate.type: trace
#server:
#  port: 9090

###=========
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/capstone2
    username: sa
    password:
    driver-class-name: org.h2.Driver
###===========
#server:
#  port: 9090
#spring:
#  datasource:
#    url: jdbc:mariadb://${TODO_MYSQL_HOST}:${TODO_MYSQL_PORT}/${TODO_DATA_BASE_NAME}?useSSL=false
#    username: ${TODO_MYSQL_USER_NAME}
#    password: ${TODO_MYSQL_PASSWORD}
#    #url: jdbc:mariadb://svc.sel5.cloudtype.app:32619/capstone2?useSSL=false
#    #username: root
#    #password: root
#    #url: jdbc:mariadb://localhost:3306/capstone2
#
#    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update   #create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace


cloud:
  aws:
    s3:
      bucket: jh-caps-bucket-7qghcbezwxrrwausy3yoorhj7baxqapn2a-s3alias
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}


    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
